openapi: '3.0.3'
info:
  title: API
  version: '1.0'
servers:
  - url: https://localhost:3000
paths:
  /auth:
    post:
      summary: Authenticate user
      description: Authenticate using email/password or OAuth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/LocalAuth'
                - $ref: '#/components/schemas/OAuthRequest'
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Authentication failed

  /users:
    post:
      summary: Register new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistration'
      responses:
        '201':
          description: User created successfully
        '400':
          description: Invalid input

  /datasets:
    post:
      summary: Create a new dataset
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - file
                - textColumn
                - targetColumn
                - labelMapping
                - type
              properties:
                file:
                  type: string
                  format: binary
                  description: CSV file containing the dataset
                mediaFiles:
                  type: string
                  format: binary
                  description: ZIP file containing media files (required if type is multimodal)
                type:
                  type: string
                  enum: [text, multimodal]
                  description: Type of dataset - text only or multimodal
                textColumn:
                  type: string
                  description: Name of the column containing text data
                targetColumn:
                  type: string
                  description: Name of the column containing target labels
                mediaPathColumn:
                  type: string
                  description: Name of the column containing paths to media files (required if type is multimodal)
                labelMapping:
                  type: object
                  description: Mapping of original labels to desired labels
                  additionalProperties:
                    type: string
                  example:
                    Y: "Yes"
                    N: "No"
      responses:
        '201':
          description: Dataset created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dataset'
        '400':
          description: Invalid input
        '401':
          description: Unauthorized

components:
  schemas:
    LocalAuth:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password

    OAuthRequest:
      type: object
      required:
        - provider
        - token
      properties:
        provider:
          type: string
          enum: [google]
        token:
          type: string

    AuthResponse:
      type: object
      properties:
        token:
          type: string
        user:
          $ref: '#/components/schemas/User'

    User:
      type: object
      properties:
        id:
          type: string
        email:
          type: string

    UserRegistration:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password

    Dataset:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        type:
          type: string
          enum: [text, multimodal]
        textColumn:
          type: string
        targetColumn:
          type: string
        mediaPathColumn:
          type: string
        labelMapping:
          type: object
          additionalProperties:
            type: string
        userId:
          type: string
        createdAt:
          type: string
          format: date-time

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer